sudo: required
services:
  - docker

before_install:
  - docker build -t crackler/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true crackler/react-test npm test

after_success:
  - docker build -t crackler/multi-client ./client
  - docker build -t crackler/multi-nginx ./nginx
  - docker build -t crackler/multi-server ./server
  - docker build -t crackler/multi-worker ./worker
  
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push crackler/multi-client
  - docker push crackler/multi-nginx
  - docker push crackler/multi-server
  - docker push crackler/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app:  multi-docker
  env:  MultiDocker-env
  bucket_name:  elasticbeanstalk-us-east-2-498385989671
  bucket_path:  docker-multi
  on:
    branch: master
  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
